version: '3.8'
name: ${NAME} # Name of docker higher level container/bridge
services:
  mc-server: # Name of specific docker container
    image: itzg/minecraft-server:java${JAVA_VERSION}
    restart: unless-stopped
    volumes:
    - ./data:/data
    - ./modpacks:/modpacks:ro
    environment:
      EULA: "true"
      TYPE: ${TYPE}
      VERSION: ${VERSION} # Needs to match minecraft version (ex: 1.7.10)
      OVERRIDE_SERVER_PROPERTIES: true
      MEMORY: ${MEMORY_ALLOC} # Memory assignment
      MODRINTH_MODPACK: ${DOCKER_MODPACK_LOCATION}
      CF_SERVER_MOD: ${DOCKER_MODPACK_LOCATION}
      CF_BASE_DIR: /data
      USE_MODPACK_START_SCRIPT: false
      DEBUG: ${DEBUG}
    ports:
      - "${SERVER_PORT}:25565" # map internal port 25565 to external port 25565
