#!/bin/bash

source definitions
INSTANCE_NAME=mc-server

case $1 in
	"install")
		./get_modpack.sh
		echo installed modpack files
		;;
	
	"start")	
		./docker_start.sh
		echo started server successfully!
		;;

	"restart")
		docker exec -i $NAME-$INSTANCE_NAME-1 rcon-cli "say 'Server restarting in 5 minutes!'"
		sleep 5m
		docker exec $NAME-$INSTANCE_NAME-1 rcon-cli stop
		echo "Restarted server!"
		;;

	"stop")
		docker exec -i $NAME-$INSTANCE_NAME-1 rcon-cli "say 'Server shutting down in 5 minutes!'"
		sleep 5m
		docker kill $NAME-$INSTANCE_NAME-1
		echo "Stopped docker server"
		;;
	"exec")
		docker exec -i $NAME-$INSTANCE_NAME-1 rcon-cli $2
		echo "Executed command $1 in container $NAME-$INSTANCE_NAME-1 successfully!"
		;;
	*)
		echo "Invalid parameter specified"
		;;
esac

